[versions]
agp = "8.7.3"
gameActivity = "4.4.2"
openxrLoader = "1.1.63"

[libraries]
game-activity = { module = "androidx.games:games-activity", version.ref = "gameActivity" }
openxr-loader = { module = "org.khronos.openxr:openxr_loader_for_android", version.ref = "openxrLoader" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
